### ISSUE TITLE
这个兼容问题能解决吗？

### ISSUE THREAD

**Issue by nenge123** [xiaozhuai/webp_encoder#4]
ios手机环境下，

CompileError: WebAssembly.Module doesn't parse at byte 3: can't get Function local's type in group 0, in function at index 234

**Comment by xiaozhuai** [comment]
iOS系统版本号发一下，我回头有空的时候看一下

**Comment by nenge123** [comment]
ios16，不过最好能兼容ios15和安卓10

**Comment by xiaozhuai** [comment]
首先我不太清楚这些系统是否支持wasm，如果支持，应该只需要做些修改就可以兼容。如果不支持wasm的话，那就没办法了。
